dist: xenial

git:
  depth: 300

language: java

jdk:
  - openjdk11

os: linux

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libxml2-utils libsaxonb-java ant

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - xmllint --noout --valid src/standards/standards.xml
  - ant -f newbuild.xml
  - ant all
  - ant debug

deploy:
  - provider: script
    skip_cleanup: true
    script: './_scripts/deploy-live-nisp.sh'
    on:
      branch: master

after_script:
  - './_scripts/trigger-site-build.sh'
