name: NISP Tools

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install XML Tools
      run: |
        sudo apt install -qq libxml2-utils libsaxonb-java ant

    - name: Generate NISP documentation
      run: |
        xmllint --noout --valid src/standards/standards.xml
        ant -f newbuild.xml
        ant all
        ant debug

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: nispworld/live-nisp
        publish_branch: master
        publish_dir: ./build
        user_name: 'nisp-bot'
        user_email: 'nisp-bot@nw3.dk'
        keep_files: true
        # cname: live.nisp.nw3.dk

    - name: Trigger NISP Nation
      env:
        TRIGGER_NISP_NATION: ${{ secrets.TRIGGER_NISP_NATION }}
      run: |
        curl -v -H "Accept: application/vnd.github.everest-preview+json" \
         -H "Authorization: token $TRIGGER_NISP_NATION" \
         --request POST \
         --data '{"event_type": "build-nation",
            "client_payload": { "MESSAGE" : "Build requested by NISP-tools" }}' \
            https://api.github.com/repos/stavnstrup/nisp-nation/dispatches
